Traceback (most recent call last):
  File "/tmp/ipykernel_2027/3678572134.py", line 68, in sweep_train
    train_loss = results['validation_0']['logloss']
KeyError: 'logloss'
